### ISSUE TITLE
Handle specific response on the extension with generic type

### ISSUE THREAD

**Issue by hoangnguyen92dn** [kaungkhantsoe/NimbleTest#10]
The `executeOrThrow()` extension is created with the generic type `<T>`, your implementation validates `LoginResponse` even though this extension is being used for different API endpoint, it means that different response classes, I think we could update to generic type for common usage instead.

https://github.com/kaungkhantsoe/NimbleTest/blob/dc472deabbd5c405e37def6289ef9822ed17cb5a/app/src/main/java/com/kks/nimbletest/util/OkHttpExt.kt#L21-L27

https://github.com/kaungkhantsoe/NimbleTest/blob/dc472deabbd5c405e37def6289ef9822ed17cb5a/app/src/main/java/com/kks/nimbletest/util/OkHttpExt.kt#L50-L58

**Comment by kaungkhantsoe** [comment]
Yes, you are right. I missed that case. I will make the update.
