### ISSUE TITLE
Common practices for effective Kotlin

### ISSUE THREAD

**Issue by hoangnguyen92dn** [kaungkhantsoe/NimbleTest#11]
Wrapping `const` with `Object` is old-fashioned with Java-style, Kotlin allows us to define the constants on the top-class level, it's a better approach to drop unnecessary `class` or `object`.

https://github.com/kaungkhantsoe/NimbleTest/blob/dc472deabbd5c405e37def6289ef9822ed17cb5a/app/src/main/java/com/kks/nimbletest/constants/AppConstants.kt#L7-L16

https://github.com/kaungkhantsoe/NimbleTest/blob/dc472deabbd5c405e37def6289ef9822ed17cb5a/app/src/main/java/com/kks/nimbletest/constants/DateConstants.kt#L7-L10

https://github.com/kaungkhantsoe/NimbleTest/blob/dc472deabbd5c405e37def6289ef9822ed17cb5a/app/src/main/java/com/kks/nimbletest/constants/PrefConstants.kt#L7-L11

Furthermore, the properties in the Request/Response data classes violate the most common Kotlin [convention](https://developer.android.com/kotlin/style-guide#non-constant_names). I understand that it matches the JSON key for serializing/deserializing the objects automatically but we could use annotation to serialize rather than leaving the properties name like this.

https://github.com/kaungkhantsoe/NimbleTest/blob/dc472deabbd5c405e37def6289ef9822ed17cb5a/app/src/main/java/com/kks/nimbletest/data/network/request/RefreshTokenRequest.kt#L7-L12

**Comment by kaungkhantsoe** [comment]
Yes, it is better. I will do the changes for them.☺️
