### ISSUE TITLE
Implement validation and loading status in the Repository layer

### ISSUE THREAD

**Issue by hoangnguyen92dn** [kaungkhantsoe/NimbleTest#12]
Following the Android app architecture fundamental, the Repository layer is responsible for handling fetching, storing,... the data for the app. Therefore, the logic to validate username and password, or loading state should be handled in the ViewModel layer instead. How do you think? 😄 

https://github.com/kaungkhantsoe/NimbleTest/blob/dc472deabbd5c405e37def6289ef9822ed17cb5a/app/src/main/java/com/kks/nimbletest/repo/login/LoginRepoImpl.kt#L29-L51

**Comment by kaungkhantsoe** [comment]
Yes, it should be handled in view model layer. Thank you for pointing that out for me. I will make the changes
