### ISSUE TITLE
Clean unused resources from the project

### ISSUE THREAD

**Issue by hoangnguyen92dn** [kaungkhantsoe/NimbleTest#7]
I see there are some classes located on the project but no reference. It would be better if we get rid of them, how do you think?

https://github.com/kaungkhantsoe/NimbleTest/blob/dc472deabbd5c405e37def6289ef9822ed17cb5a/app/src/main/res/transition/change_image_transform.xml#L1-L4

https://github.com/kaungkhantsoe/NimbleTest/blob/dc472deabbd5c405e37def6289ef9822ed17cb5a/app/src/main/java/com/kks/nimbletest/util/interceptors/FakeCallInterceptor.kt#L14-L35

**Comment by kaungkhantsoe** [comment]
Thanks for point that out. I was trying various things and forgot to clean those up.😅 I will make a change.
